
spring.application.name=studentmanagmentsystem1
spring.datasource.url=jdbc:postgresql://localhost:5432/studentmanagementsystem1
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# jwt.secret=12d22c1a419e81fdfdb9a085c202047e0aa644bd5ab280e537e31bcd3dbf5b41
# jwt.expiration=86400000


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081
logging.level.com.example.studentmanagmentsystem1=DEBUG
logging.level.org.hibernate.SQL=DEBUG



